### PR TITLE
Amend Standard Governance with additional Patent Application Disclosure and Good Faith requirements

### PR DESCRIPTION
**Pull request by openfin-gavin**
The Governance of the FINOS Standards Project Blueprint currently does not adequately address important IP issues that can affect all FINOS standards projects.  These IP issues are currently impacting the FDC3 project which is the most established standards project within FINOS:

No Disclosure Requirement: The Governance does not require Working Group participants to disclose that they have filed a patent application relating to the work product of the Working Group. This is part of the governance for the World Wide Web Consortium (W3C).

No Bad Faith Deterrent: The Governance does not disallow Working Group participants from filing patents on the work product of a Working Group. Any participant is free to write down what is produced in Working Group meetings and file patents on the information.

Infringement Grey Area: The policies are unclear as to whether implementers of a standard are protected from patents if they implement something similar to a specification, but not the specification exactly.  For example, many banks, buy-side and vendors currently have “flavors” of FDC3 that do not fully conform to the specification.

These issues place all FINOS standard implementers at risk.  To address the issue above, we propose to add a 6th section to the Governance document covering Patent Application Disclosure; Good Faith

### CODE REVIEW

**Comment by lspiro-Tick42** [comment]
My view is that these issues are important to consider. 

I personally do not agree that FDC3 is currently impacted. I also feel (as someone with absolutely zero legal training) that the concepts contained in FDC3 have been around for so long that any patent could be challenged on the basis of prior art, but as much as I like lawyers as people, no one wants to get involved in a US patent case.

So in that respect,  I would be very interested in the opinion of the people in this group about whether the cases described by Gavin could be raised by a patent holder.  And if they can, whether protection could be added to the project blueprint.

**Comment by mindthegab** [comment]
Thanks @openfin-gavin for proposing the verbiage and outlining the concerns.

I welcome input from Members and maintainers on this issue (please do reach out to me directly in case you are not able to post on GitHub and I’d be happy to relay here).

I’ll also solicit input of the Membership and Governance committee and Governing Board appropriate (the next meeting is on Jan 19th).

**Comment by mindthegab** [comment]
@openfin-gavin @mazydar Again, thanks for bringing these changes forward. 

After LF Legal review and a further conversation with you, I have reflects amended verbiage you are agreeable with in this [pull request](https://github.com/openfin-gavin/standards-project-blueprint/pull/1) to include the following changes:

1. Restrict disclosure requirement to Necessary Claims and only to patents Participants are aware of 
2. Move Code of Conduct amendments in the Code_of_Conduct file. 

If you merge that pull requests, these changes should flow directly here so we have a consolidated history of the conversation.  Note: I also renamed this PR, so it's more reflective of the intent, please let me know if I misrepresented anything.

As previously discussed, I plan to bring these changes for Governing Board discussion and determination next week at the 1/19 GB meeting.

**Comment by mindthegab** [comment]
Thanks @openfin-gavin for the quick action here. Proposed changes are now merged and available for review at https://github.com/finos/standards-project-blueprint/pull/4/files.

Will post back outcomes of the Governing Board discussion happening on Jan 19th.

**Comment by mindthegab** [comment]
@openfin-gavin @mazydar

On behalf of the FINOS Governing Board, I wanted to provide an update following the GB meeting of January 19th, where this PR's proposed changes were presented and a lively discussion ensued.

The executive summary is that there was no consensus to move forward with these changes "as is". 

Several GB representatives identified a criticality in the proposal, in that the concept of "awareness of a patent" has the potential to make large organizations very concerned that they might be accused of failing to disclose a patent that had in fact resulted from research completely independent of a FINOS working group. Also, the upside for making this change was not immediately apparent to the GB (given undisclosed Necessary Claims must already be licensed anyway to compliant implementations).

As next step, we will convene a meeting of the Membership & Governance committee, extended with participation of interested GB members (several of them expressed interest), in short order and discuss these issues further and give you a chance to make directly the case to an engaged and informed group. I expect this to happen by mid-Feb. 

We will post further updates on this PR as they become available.

Thanks everyone for chiming in!

**Comment by openfin-gavin** [comment]
Pushed a new change that addresses the concern that firms with large patent portfolios may have around disclosure requirements. We now propose narrower language that only requires disclosure if the participant in the Working Group meeting has knowledge of a patent.

**Comment by mindthegab** [comment]
Thanks @openfin-gavin.

Providing an update here after the Feb 16th M&G Committee - there was general support for this amended changes to be sent for Governing Board vote. We're ironing out additional changes [regarding the infringement gray area](https://github.com/finos/standards-project-blueprint/pull/8) and then we plan to send for vote. 

Please note this might mean we're forking from the upstream community specification.

Keep you posted!

**Comment by mindthegab** [comment]
Providing an update here, a Governing Board email vote is now underway and will close on April 8th. I'll post updates once it's closed.

[EDIT]
The VOTE was extended until April 20th 2022 due to low number of responses.

**Comment by mindthegab** [comment]
@openfin-gavin and Community, 

Thanks for your patience here as the FINOS Governing Board deliberated on this proposal. The electronic VOTE closed on April 20th COB and this amendment has been **REJECTED**, so I will now proceed to close this pull request without merging.

Here's the details of the vote:

- **Total Governing Board Representatives:** 17 (11 Platinum, 4 Gold, 1 Silver, 1 ED)
- **Passing requirement:** 9 (for electronic votes, the majority of all representatives per [section 6.c of our Charter](https://www.finos.org/hubfs/FINOS%20Charter.pdf))
- **Total votes received**: 14
   - Votes breakdown: 6 x 👍
   - 6 x  abstentions
   - 2 x 👎

Thanks @openfin-gavin and everyone involved in this proposal. I know this is of course not your desired outcome, but  I hope you will appreciate the extent the FINOS Governing Board has gone to evaluate this proposal, through multiple reviews at 3 meetings, 2 Membership & Governance Committees and an extended electronic vote (our first!).

**Pull request closed without merging**
